# Generated by Django 4.2.7 on 2023-11-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(help_text='Įveskite automobilio markę', max_length=40, verbose_name='Automobilio markė')),
                ('modelis', models.CharField(help_text='Įveskite automobilio markės modelį', max_length=40, verbose_name='Automobilio modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Įveskite valstybinį numerį', max_length=7, unique=True, verbose_name='Automobilio valstybinis Nr.')),
                ('vin_kodas', models.CharField(help_text='Įveskite automobilio VIN kodą', max_length=17, unique=True)),
                ('klientas', models.CharField(help_text='Iveskite klientą (įmonės pavadinimas arba vardas/pavardė)', max_length=100)),
                ('automobilio_modelis_id', models.ForeignKey(db_column='automobilio_modelis', on_delete=django.db.models.deletion.PROTECT, to='autoservisas.automobilio_modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Įveskite paslaugos pavadinimą', max_length=200, unique=True, verbose_name='Paslaugos pavadinimas')),
                ('kaina', models.FloatField(help_text='Įveskite paslaugos kainą', max_length=10, verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Užsakymo data')),
                ('automobilis_id', models.ForeignKey(db_column='informacija', on_delete=django.db.models.deletion.PROTECT, to='autoservisas.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(help_text='Įveskite kiekį')),
                ('paslauga_id', models.OneToOneField(db_column='paslauga', on_delete=django.db.models.deletion.PROTECT, to='autoservisas.paslauga')),
                ('uzsakymas_id', models.ForeignKey(db_column='uzsakymo_informacija', on_delete=django.db.models.deletion.PROTECT, to='autoservisas.uzsakymas')),
            ],
        ),
    ]
