# Generated by Django 4.2.7 on 2023-11-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_alter_automobilis_automobilio_modelis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='automobilio_modelis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoservisas.automobilio_modelis', verbose_name='automobilio modelis'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoservisas.automobilis', verbose_name='informacija'),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='paslauga_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autoservisas.paslauga', verbose_name='paslauga'),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='uzsakymas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoservisas.uzsakymas', verbose_name='uzsakymo informacija'),
        ),
    ]
