# Generated by Django 4.2.7 on 2023-11-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_alter_automobilis_automobilio_modelis_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Automobilio_modelis',
            new_name='AutomobilioModelis',
        ),
        migrations.RenameModel(
            old_name='Uzsakymo_eilute',
            new_name='UzsakymoEilute',
        ),
    ]
