# Generated by Django 4.2.7 on 2023-11-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0007_alter_uzsakymoeilute_uzsakymas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='automobilio_modelis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.automobiliomodelis', verbose_name='Automobilio modelis'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.automobilis', verbose_name='Informacija'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='paslauga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.paslauga', verbose_name='Paslauga'),
        ),
    ]
