# Generated by Django 4.2.7 on 2023-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0011_alter_uzsakymas_statusas'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='nuotrauka',
            field=models.ImageField(null=True, upload_to='nuotraukos', verbose_name='Nuotrauka'),
        ),
    ]
