# Generated by Django 4.2.7 on 2023-11-15 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisas', '0012_automobilis_nuotrauka'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='vartotojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
