# Generated by Django 4.2.7 on 2023-11-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0013_uzsakymas_vartotojas'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='grazinimo_terminas',
            field=models.DateField(blank=True, null=True, verbose_name='Prognozuojama atlikimo data'),
        ),
    ]
