# Generated by Django 4.2.7 on 2023-11-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0015_automobilis_aprasymas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='autoservisas.automobilis', verbose_name='Informacija'),
        ),
    ]
